# https://modrinth.com/mod/modernfix/versions
modernfix_version = 5.23.1+mc1.21.1

# https://modrinth.com/mod/geckolib/versions?g=1.21.1
geckolib_version = 4.7.5.1

# https://modrinth.com/mod/sophisticated-core-(unofficial-fabric-port)/versions
sophisticatedcore_version = 1.21.1-1.2.9.14.154

# https://modrinth.com/mod/modernkeybinding/versions
## TODO: not updated!
mkb_version = 1.20.X-1.2.0

# https://modrinth.com/mod/sophisticated-core-(unofficial-fabric-port)/versions
sophisticatedcore_version = 1.21.1-1.2.9.14.154

# https://modrinth.com/mod/creativecore/versions?l=fabric&g=1.21.1
creativecore_version = wQecY0h2

## TODO: not updated!
amecsapi_version = 1.5.3+mc1.20-pre1

# https://modrinth.com/mod/emi/versions?l=fabric&g=1.20.1
emi_version = 1.1.22+1.20.1

# https://modrinth.com/mod/jei/versions?l=fabric&g=1.20.1
jei_version = 15.20.0.112

# https://modrinth.com/mod/rei/versions?l=fabric&g=1.20.1
rei_version = 12.1.785