# https://modrinth.com/mod/modernfix/versions
modernfix_version = 5.23.0+mc1.20.1

# https://modrinth.com/mod/geckolib/versions?g=1.20.1
geckolib_version = 4.7.1.2

# https://modrinth.com/mod/modernkeybinding/versions
mkb_version = 1.20.X-1.2.0

# https://modrinth.com/mod/sophisticated-core-(unofficial-fabric-port)/versions
sophisticatedcore_version = 1.20.1-1.2.7.7.156