# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.16.14

# Mod Properties
# Versioning is handled automatically by buildscript.
maven_group=xyz.bluspring
archives_base_name=Kilt
publishing.modrinth = t87XZEqv
publishing.curseforge = 1295823

# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
parchment_version=1.20.1
parchment_release=2023.09.03


### Dependencies

# https://modrinth.com/mod/fabric-language-kotlin/versions
fabric_kotlin_version=1.13.4+kotlin.2.2.0

# https://fabricmc.net/develop/
fabric_version=0.92.4+1.20.1

# https://modrinth.com/mod/forge-config-api-port/versions
forgeconfigapiport_version=8.0.2

# https://modrinth.com/mod/architectury-api/versions
architectury_version=9.2.14

# https://modrinth.com/mod/sodium/versions
sodium_version = mc1.20.1-0.5.13-fabric

# https://modrinth.com/mod/indium/versions
indium_version = 1.0.36+mc1.20.1

# https://modrinth.com/mod/iris/versions
iris_version = 1.7.6+1.20.1


### Bundled

## Fabric Mods
# https://github.com/thecatcore/CursedMixinExtensions/tags
cursedmixinextensions_version=1.1.0

# https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.5.0-beta.5

# https://github.com/Chocohead/Fabric-ASM/blob/master/build.gradle#L29
fabric_asm_version=2.3

# https://github.com/Bawnorton/MixinSquared/releases
mixin_squared_version=0.3.3

# https://mvnrepository.com/artifact/de.florianmichael/AsmFabricLoader
asmfabricloader_version=1.1.7

# https://github.com/Moulberry/MixinConstraints
mixinconstraints_version=1.0.8

# https://mvn.devos.one/#/releases/io/github/fabricators_of_create/Porting-Lib/base
porting_lib_version=2.3.8+1.20.1

# https://mvn.devos.one/#/snapshots/io/github/tropheusj/serialization-hooks
# serialization_hooks_version=0.4.27

# https://maven.jamieswhiteshirt.com/libs-release/com/jamieswhiteshirt/reach-entity-attributes/
reach_entity_attributes_version=2.4.0

# https://maven.fabricmc.net/teamreborn/energy/
teamreborn_energy_version=3.0.0

## Libraries
# custom fork - https://mvn.devos.one/#/snapshots/xyz/bluspring/eventbus
eventbus_version=6.2.17

# https://files.minecraftforge.net/net/minecraftforge/forgespi/index.html
forgespi_version=7.1.3

# custom fork - https://mvn.devos.one/#/snapshots/xyz/bluspring/AutoRenamingTool
forgerenamer_version=0.1.52

# custom fork - https://mvn.devos.one/#/snapshots/xyz/bluspring/srgutils
srgutils_version = 0.5.15

# https://maven.fabricmc.net/net/fabricmc/tiny-remapper/
tiny_remapper_version = 0.11.1

# custom fork - https://mvn.devos.one/#/snapshots/cpw/mods/securejarhandler
securejarhandler_version=fabric-2.1.6

# https://mvnrepository.com/artifact/org.openjdk.nashorn/nashorn-core
nashorn_version=15.4

# https://github.com/thedarkcolour/KotlinForForge/tree/site/thedarkcolour/kfflang/4.10.0
kff_version = 4.10.0