mod_version = 1.0.0

# https://modrinth.com/mod/trinkets/versions?g=1.21.1
trinkets_version = 3.10.0
# https://modrinth.com/mod/curios/versions?g=1.21.1
curios_version = 9.5.1+1.21.1
# https://modrinth.com/mod/immersiveengineering/versions?g=1.21.1
immersiveengineering_version = 12.3.1-189
# https://modrinth.com/mod/structure-gel-api/versions?g=1.21.1
## TODO: not updated!
structuregelapi_version = 2.16.2