mod_version = 1.0.0

# https://modrinth.com/mod/trinkets/versions?g=1.20.1
trinkets_version = 3.7.2
# https://modrinth.com/mod/curios/versions?g=1.20.1
curios_version = 5.14.1+1.20.1
# https://modrinth.com/mod/immersiveengineering/versions?g=1.20.1
immersiveengineering_version = 10.2.0-183
# https://modrinth.com/mod/quark/versions?g=1.20.1
quark_version = 1.20.1-4.0-462
# https://maven.blamejared.com/org/violetmoon/zeta/Zeta/maven-metadata.xml
zeta_version = 1.0-29.135
# https://modrinth.com/mod/structure-gel-api/versions?g=1.20.1
structuregelapi_version = 2.16.2