name: Crash Report
description: "Experiencing a crash in Kilt?"
labels:
  - T-crash
  - S-needs triage
# This has been modified from https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1
# and https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/.github/ISSUE_TEMPLATE/crash_report.yml?plain=1
body:
  - type: markdown
    attributes:
      value: >-
        ## Instructions


        This is a template for the issue you are about to open! This will help you
        provide the information necessary to complete your **crash report**.
        Before you open an issue, make sure that you've completed every step on the
        checklist below.


        - [Have you searched around](https://github.com/KiltMC/Kilt/issues) to find any
        similar issues? If you find one that looks like what you are getting,
        consider contributing additional information to it instead. Make sure
        you are not opening a duplicate issue.

        - Are you using the latest version of the mod? If not, try updating to
        see if it resolves your issue.


        All good? Then continue to fill the issue by providing the following
        information about it:
  - type: input
    id: version
    attributes:
      label: Version information
      description: >-
        Please provide the exact version of the mod you are using. Every part of
        the version is important! If you do not know what version you are using,
        look at the file name in your `mods` folder.
      placeholder: 'Example: 0.0.1.3+mc1.19.2'
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: >-
        Provide information on how to reproduce this bug. You can either
        fill this section in like the example below or do something else just
        make sure your instructions are minimal and clear, as other people will
        need to be able to replicate your issue.
      placeholder: |
        Example:
        1. Place a Redstone Lamp in front of a Redstone Repeater
        2. Use a Lever to activate the Redstone Repeater
        3. Nothing happens
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: Java version
      placeholder: 'Example: Java 17'
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: Crash Report file
      description: >-
          Upload your crash report file as an attachment to this issue (drag-and-drop) or to a service such as GitHub
          Gist (paste a link) and replace this section. This information is critical in resolving your issue!

          Messages like "Exit code 0" from your launcher are not what you're looking for. If your launcher does not
          provide a button to view the most recent crash report, check your game's `crash-reports` folder for the most recent
          crash report file. If you did not manage to find any, send the `latest.log` file from your game's `logs` folder.
      validations:
        required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >-
        Provide a list of any other mods you are using, along with their
        respective versions. If you have any screenshots, videos, or other
        information that you feel is necessary to explain the issue, feel free
        to attach them here.