name: Gradle CI

on:
  push:
    branches:
      - 'version/*'

permissions:
  contents: read

jobs:
  build:
    environment: Kilt Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ github.token }}
        fetch-depth: 0
        filter: tree:0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - name: Build artifacts
      run: ./gradlew remapJar
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        archive: false
        name: Kilt Built Jar
        path: build/libs/Kilt-*.jar
