name: Kilt Release

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build:
    environment: Kilt Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ github.token }}
          fetch-depth: 0
          filter: tree:0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - name: Publish artifacts
        env:
          GITHUB_TAG: ${{ github.ref_name }}
          RELEASE_DESCRIPTION: ${{ github.event.release.body }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew publishMods -Pbuild.release=true
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
